dbt_scripts:
  outputs:
    dev:
      dbname: "{{ env_var('DWH_NAME_DEV') }}"
      host: "{{ env_var('DWH_HOST_DEV') }}"
      pass: "{{ env_var('DWH_PWD_DEV') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DWH_USER_DEV') }}"
    test:
      dbname: "{{ env_var('DWH_NAME_TEST') }}"
      host: "{{ env_var('DWH_HOST_TEST') }}"
      pass: "{{ env_var('DWH_PWD_TEST') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DWH_USER_TEST') }}"
    prod:
      dbname: "{{ env_var('DWH_NAME_PROD') }}"
      host: "{{ env_var('DWH_HOST_PROD') }}"
      pass: "{{ env_var('DWH_PWD_PROD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DWH_USER_PROD') }}"
  target: dev
