{{
  config(
    materialized = "table"
  )
}}

WITH RAW_CI_CIRCUITS AS (
    SELECT DISTINCT *
    FROM PUBLIC."RSG_CI_CIRCUITS"
)
SELECT
    "ID" AS ID_CI_CIRCUITS,
    "NOM" AS NOMBRE,
    "OBSERVACIONS" AS OBSERVACIONES,
    "DATA_ACTUALITZACIO" AS DATA_ACTUALIZACION,
    "ID_USUARI_ACTUALITZACIO" AS ID_USUARIO_ACTUAALIZACION
FROM RAW_CI_CIRCUITS
