{{
  config(
    materialized = "table"
  )
}}

WITH RAW_ACCESO_EXTERNO AS (
    SELECT * FROM PUBLIC."RSG_ACCES_EXTERNS"
)
SELECT
    "ID_ACCES_EXTERNS",
    "USUARI",
    "ROLES",
    "MOTIVO",
    "ACCESO",
    TO_DATE("DATA_ACCES", 'DD/MM/YY') AS "DATA_ACCESO",
    "RESULTADO",
    "ID_EXPEDIENT",
    "NUM_DOCUMENT"
FROM RAW_ACCESO_EXTERNO
